import postSlice, {
  setPost,
  setPostLoading,
  setIsCommentType,
  setSkip,
  setCommentLoading,
  setComments,
  setIsEnd,
  addComment,
  addActionsComments,
  togglePostLike,
  togglePostThreadLike,
  togglePostCommentLike,
  togglePostBookmark,
  togglePostThreadBookmark,
  togglePostCommentBookmark,
} from "./postSlice";

export {
  postSlice,
  setPost,
  setPostLoading,
  setIsCommentType,
  setSkip,
  setCommentLoading,
  setComments,
  setIsEnd,
  addComment,
  addActionsComments,
  togglePostLike,
  togglePostThreadLike,
  togglePostCommentLike,
  togglePostBookmark,
  togglePostThreadBookmark,
  togglePostCommentBookmark,
};
