import {
  EMPTY,
  PASSWORD_FORBIDDEN,
  PASSWORD_UNDER_MINIMUM,
  PASSWORD_INCOMPLETE,
  USERNAME_UNDER_MINIMUM,
  EMAIL_FORMAT,
} from "./regExps"; // 정규 표현식
import {
  PASSWORD_MAX,
  PASSWORD_MIN,
  PASSWORD_SPECIAL_CHARECTERS,
  USERNAME_MAX,
  USERNAME_MIN,
  EMAIL_SPECIAL_CHARACTERS,
} from "./constants"; // 상수

export {
  // 정규 표현식
  EMPTY,
  PASSWORD_FORBIDDEN,
  PASSWORD_UNDER_MINIMUM,
  PASSWORD_INCOMPLETE,
  USERNAME_UNDER_MINIMUM,
  EMAIL_FORMAT,

  // 상수
  PASSWORD_MAX, // 비밀번호 최대 길이
  PASSWORD_MIN, // 비밀번호 최소 길이
  PASSWORD_SPECIAL_CHARECTERS,
  USERNAME_MAX,
  USERNAME_MIN,
  EMAIL_SPECIAL_CHARACTERS, // 이메일 로컬에서 사용 가능한 특수문자
};
