const PRIMARY_LINK = {
  AUTH: "/",
  HOME: "/home",
  EXPLORE: "/explore",
  NOTIFICATIONS: "/notifications",
  MESSAGES: "/messages",
  PROFILE: "/:userId",
  SETTINGS: "/settings",
  COMPOSE_POST: "/compose/post",
  SCHEDULE_POST: "/compose/post/schedule",
  UNSENT_POST: "/compose/post/unsent",
  SCHEDULED_POST: "/compose/post/unsent/scheduled",
  DRAFT_POST: "/compose/post/unsent/drafts",
  LOGOUT: "/logout",
  FLOW: "/i/flow",
  LOGIN: "/i/flow/login",
  SIGNUP: "/i/flow/signup",
  ACCOUNT_MANAGE: "/account/manage",
  PASSWORD_RESET: "/i/flow/password_reset",
  VERIFY_OWNERSHIP: "/i/flow/verify_account_ownership",
  POSTPAGE: "/:userId/status/:postId",
  POSTPAGE_QUOTES: "quotes",
  POSTPAGE_ANALYTICS: "analytics",
  SEARCH: "/search",
};

export default PRIMARY_LINK;
