const PRIMARY_LINK = {
  AUTH: "/",
  HOME: "/home",
  EXPLORE: "/explore",
  EXPLORE_FORYOU: "tabs/for_you",
  EXPLORE_TRENDING: "tabs/trending",
  EXPLORE_NEWS: "tabs/news",
  EXPLORE_SPORTS: "tabs/sports",
  EXPLORE_ENTERTAINMENT: "tabs/entertainment",
  NOTIFICATIONS: "/notifications",
  MESSAGES: "/messages",
  PROFILE: "/:userId",
  SETTINGS: "/settings",
  COMPOSE_POST: "/compose/post",
  SCHEDULE_POST: "/compose/post/schedule",
  UNSENT_POST: "/compose/post/unsent",
  SCHEDULED_POST: "/compose/post/unsent/scheduled",
  DRAFT_POST: "/compose/post/unsent/drafts",
  LOGOUT: "/logout",
  FLOW: "/i/flow",
  LOGIN: "/i/flow/login",
  SIGNUP: "/i/flow/signup",
  ACCOUNT_MANAGE: "/account/manage",
  PASSWORD_RESET: "/i/flow/password_reset",
  VERIFY_OWNERSHIP: "/i/flow/verify_account_ownership",
  POSTPAGE: "/:userId/status/:postId",
  POSTPAGE_QUOTES: "quotes",
  POSTPAGE_ANALYTICS: "analytics",
  SEARCH: "/search",
  SEARCH_SETTINGS: "/settings/search",
  SEARCH_ADVANCED: "/search/advanced",
  PROFILE_SETTINGS: "/settings/profile",
};

export default PRIMARY_LINK;
