const SETTINGS_LINKS = {
  ACCOUNT: "account",
  SECURITY_AND_ACCOUNT_ACCESS: "security_and_account_access",
  PRIVACY_AND_SAFETY: "privacy_and_safety",
  NOTIFICATIONS: "notifications",
  ACCESSIBILITY_DISPLAY_AND_LANGUAGES: "accessibility_display_and_languages",
  ACCOUNT_INFO: "your__data/account",
  PASSWORD: "password",
  DOWNLOAD_DATA: "download_your_data",
  DEACTIVATE: "deactivate",
  SECURITY: "security",
  APPS_AND_SESSIONS: "apps_and_sessions",
  CONNECTED_ACCOUNTS: "connected_accounts",
  DELEGATE: "delegate",
  AUDIENCE_AND_TAGGING: "audience_and_tagging",
  MY_POSTS: "my_posts",
  CONTENT_I_SEE: "content_i_see",
  MUTE_AND_BLOCK: "mute_and_block",
  DIRECT_MESSAGES: "direct_messages",
  CONTACTS: "contacts",
  ADS_PREFERENCES: "ads_preferences",
  LOCATION_INFORMATION: "location_information",
  NOTIFICATIONS_FILTERS: "notifications/filters",
  NOTIFICATIONS_PREFERENCES: "notifications/preferences",
  ACCESSIBILITY: "accessibility",
  DISPLAY: "display",
  LANGUAGE: "language",
  DATA: "data",
  SCREEN_NAME: "screen_name",
  PHONE: "phone",
  EMAIL: "email",
  COUNTRY: "country",
  LANGUAGES: "languages",
  GENDER: "gender",
  AGE: "age",
};

export default SETTINGS_LINKS;
