import {
  setUsernameInSignup,
  setPhoneInSignup,
  setPhoneOauthInSignup,
  setEmailInSignup,
  setEmailOauthInSignup,
  setBirthInSignup,
  setBirthYearInSignup,
  setBirthMonthInSignup,
  setBirthDateInSignup,
  setPasswordInSignup,
  setUserIdInSignup,
  setProfileImageInSignup,
  setNotificationsInSignup,
  setLanguageInSignup,
  setNotificationsMessagesInSignup,
  setNotificationsRepliesInSignup,
  setNotificationsNewFollowerInSignup,
  setNotificationsPostsInSignup,
  setDeviceInSignup,
  setIpInSignup,
  setLocationInSignup,
  setGenderInSignup,
} from "./signupSlice";

import { loginRequset, loginSuccess, loginFailure } from "./loginSlice";

export {
  // signup
  setUsernameInSignup,
  setPhoneInSignup,
  setPhoneOauthInSignup,
  setEmailInSignup,
  setEmailOauthInSignup,
  setBirthInSignup,
  setBirthYearInSignup,
  setBirthMonthInSignup,
  setBirthDateInSignup,
  setPasswordInSignup,
  setUserIdInSignup,
  setProfileImageInSignup,
  setNotificationsInSignup,
  setLanguageInSignup,
  setNotificationsMessagesInSignup,
  setNotificationsRepliesInSignup,
  setNotificationsNewFollowerInSignup,
  setNotificationsPostsInSignup,
  setDeviceInSignup,
  setIpInSignup,
  setLocationInSignup,
  setGenderInSignup,

  // login
  loginRequset,
  loginSuccess,
  loginFailure,
};
