import searchSlice, {
  setSearchHistory,
  toggleSavedSearches,
  setSearchLoading,
  setKeywordResult,
  toggleRecentSearches,
  clearRecentSearches,
  setKeyword,
  setAllKeywords,
  setPhrase,
  setAnyKeywords,
  setExcludeKeywords,
  setHashtags,
  setFromAccounts,
  setToAccounts,
  setMentionsToAccounts,
  toggleFilterComments,
  setFilterComments,
  toggleFilterLinks,
  setFilterLinks,
  setEngageMinComments,
  setEngageMinLikes,
  setEngageMinReposts,
  setPeriodSinceYear,
  setPeriodSinceMonth,
  setPeriodSinceDate,
  setPeriodUntilYear,
  setPeriodUntilMonth,
  setPeriodUntilDate,
  setAdvancedSearch,
} from "./searchSlice";

export {
  //slice
  searchSlice,

  // reducers
  setSearchHistory,
  toggleSavedSearches,
  setSearchLoading,
  setKeywordResult,
  toggleRecentSearches,
  clearRecentSearches,
  setKeyword,
  setAllKeywords,
  setPhrase,
  setAnyKeywords,
  setExcludeKeywords,
  setHashtags,
  setFromAccounts,
  setToAccounts,
  setMentionsToAccounts,
  toggleFilterComments,
  setFilterComments,
  toggleFilterLinks,
  setFilterLinks,
  setEngageMinComments,
  setEngageMinLikes,
  setEngageMinReposts,
  setPeriodSinceYear,
  setPeriodSinceMonth,
  setPeriodSinceDate,
  setPeriodUntilYear,
  setPeriodUntilMonth,
  setPeriodUntilDate,
  setAdvancedSearch,
};
