import { explore_lang } from "./data";
import { SearchContextProvider, SearchContext } from "./context";
import { ISearchContext, IRect } from "./types";
import {
  SearchKeyword,
  SearchContainer,
  Search,
  SearchDropdown,
  SearchSettingsContainer,
  SearchSettingsIcon,
  SearchSettingsDropdown,
  SearchSuggestionList,
  SearchSuggestion,
  AutoCompleteList,
  AutoCompleteKeyword,
  AutoCompleteAccount,
  ClearKeywordsConfirm,
  ExploreSettingModal,
  LocationModal,
  SearchSettingsModal,
  SearchFilterModal,
  SearchAdvancedModal,
} from "./ui";
import {
  useSearchContext,
  useSearch,
  useClickOutside,
  searchSlice,
  setSearchHistory,
  getSearchHistory,
  toggleSavedSearches,
  selectSavedSearches,
  setSearchLoading,
  selectSearchLoading,
  setKeywordResult,
  selectSearchSuggestion,
  toggleRecentSearches,
  selectAutoCompleteList,
  useKeyword,
  clearRecentSearches,
  setKeyword,
  selectKeyword,
  selectAllKeywords,
  selectPhrase,
  selectAnyKeywords,
  selectExcludeKeywords,
  selectHashtags,
  setPhrase,
  setAnyKeywords,
  setExcludeKeywords,
  setHashtags,
  selectSearchAdvanced,
  setAllKeywords,
  setFromAccounts,
  setToAccounts,
  setMentionsToAccounts,
  toggleFilterComments,
  setFilterComments,
  toggleFilterLinks,
  setFilterLinks,
  setEngageMinComments,
  setEngageMinLikes,
  setEngageMinReposts,
  setPeriodSinceYear,
  setPeriodSinceMonth,
  setPeriodSinceDate,
  setPeriodUntilYear,
  setPeriodUntilMonth,
  setPeriodUntilDate,
  selectFromAccounts,
  selectToAccounts,
  selectMentionToAccounts,
  selectFilterComments,
  selectFilterLinks,
  selectMinComments,
  selectMinLikes,
  selectMinReposts,
  selectPeriodSince,
  selectPeriodUntil,
  selectAdvancedKeywords,
  selectAdvancedAccounts,
  selectAdvancedFilter,
  selectAdvancedEngagement,
  selectAdvancedPeriod,
} from "./models";
import { debounce } from "./utils";

export {
  // data
  explore_lang,

  // context
  SearchContext,
  SearchContextProvider,

  // hooks
  useSearchContext,
  useSearch,
  useClickOutside,
  useKeyword,

  // slice
  searchSlice,

  // reducers
  setSearchHistory,
  toggleSavedSearches,
  setSearchLoading,
  setKeywordResult,
  toggleRecentSearches,
  clearRecentSearches,
  setKeyword,
  setPhrase,
  setAnyKeywords,
  setExcludeKeywords,
  setHashtags,
  setAllKeywords,
  setFromAccounts,
  setToAccounts,
  setMentionsToAccounts,
  toggleFilterComments,
  setFilterComments,
  toggleFilterLinks,
  setFilterLinks,
  setEngageMinComments,
  setEngageMinLikes,
  setEngageMinReposts,
  setPeriodSinceYear,
  setPeriodSinceMonth,
  setPeriodSinceDate,
  setPeriodUntilYear,
  setPeriodUntilMonth,
  setPeriodUntilDate,

  // selectors
  getSearchHistory,
  selectSavedSearches,
  selectSearchLoading,
  selectSearchSuggestion,
  selectAutoCompleteList,
  selectKeyword,
  selectPhrase,
  selectAnyKeywords,
  selectExcludeKeywords,
  selectHashtags,
  selectSearchAdvanced,
  selectAllKeywords,
  selectFromAccounts,
  selectToAccounts,
  selectMentionToAccounts,
  selectFilterComments,
  selectFilterLinks,
  selectMinComments,
  selectMinLikes,
  selectMinReposts,
  selectPeriodSince,
  selectPeriodUntil,
  selectAdvancedKeywords,
  selectAdvancedAccounts,
  selectAdvancedFilter,
  selectAdvancedEngagement,
  selectAdvancedPeriod,

  // utils
  debounce,

  // ui
  SearchContainer,
  Search,
  SearchDropdown,
  SearchKeyword,
  SearchSettingsContainer,
  SearchSettingsIcon,
  SearchSettingsDropdown,
  SearchSuggestionList,
  SearchSuggestion,
  AutoCompleteList,
  AutoCompleteKeyword,
  AutoCompleteAccount,
  ClearKeywordsConfirm,
  ExploreSettingModal,
  LocationModal,
  SearchSettingsModal,
  SearchFilterModal,
  SearchAdvancedModal,
};

export type { ISearchContext, IRect };
